locales:
  en:
    name: Eastern Canadian Inuktitut Keyboards
    description: >-
      Mobile OS keyboards for the Eastern Canadian Inuktitut language from the
      Divvun group at UiT.
  nb:
    name: Eastern Canadian Inuktitut tastatur
    description: Mobiltastatur for Eastern Canadian Inuktitut fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
