template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 10
template_sha = "0c5872ed970a80bb2ae33befe55b90615be6299f"

[replacements]
__UND2C__ = "ike"
__UNDEFINED__ = "Eastern Canadian Inuktitut"
__UND__ = "ike"
