template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 18
template_sha = "3dc402e19368b65f5a7ecb7490d8669cc2537134"

[replacements]
__UND2C__ = "ike"
__UNDEFINED__ = "Eastern Canadian Inuktitut"
__UND__ = "ike"
