template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 8
template_sha = "3b4543a6bc07357e1ce8f8a1e7bba3c728c17c07"

[replacements]
__UND2C__ = "ike"
__UNDEFINED__ = "Eastern Canadian Inuktitut"
__UND__ = "ike"
