template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 31
template_sha = "d5913dafed6bbd7a0ea4fe7f3c27a65bd174eb37"

[replacements]
__UND2C__ = "ike"
__UNDEFINED__ = "Eastern Canadian Inuktitut"
__UND__ = "ike"
